version: "3.7"

services:
  backend:
    build: ./api_imoveis
    ports:
      - "3333:3333"
    volumes:
      - "./api_imoveis:/backend"
    links:
      - database
    command: npm run dev

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./api_imoveis/database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  app:
    build: ./front_imoveis
    ports:
      - "3000:3000"
    volumes:
      - "./front_imoveis:/app"
    links:
      - backend
    command: npm start
